### ISSUE TITLE
(WHOLE TEAM) Improve map journey on mobile

### ISSUE THREAD

**Issue by KirstyScott** [visitscotland/vs-component-library#105]
On mobile users had a few problems interacting with the map (because you don't see the map and the panel at the same time - as you do on desktop).

The user journey is clunky and at times unexpected. Can we review the current journey on mobile and improve the experience for our users.
-  *Dev/ FUNCTIONALITY:* On maps with the toggle (places/regions) this toggle is not always relevant and should be turned off (ie for outlander map on mobile) - DONE BUT NOT RELEASED
-  *Design/UI:* The open search and filter button looks more like a label and users were not using it. Can we look to improve micro copy (it is not a search function so that is confusing. Consider "open map filters" as an alternative.
-  *Dev/ FUNCTIONALITY:* If a user selects a pin it opens the card for that pin, the back button on this card takes you to the list of items (ie castles) that the card relates to. If the user accessed this card via the map then this is confusing, consider adding micro copy with arrow to state "filters" or similar so it jumps to category list instead. the back button should only go back to a view the user has seen before otherwise is unexpected. Can we look at that? (this is confusing so I will add a screen shot to try demonstrate the user journey).
 - *UX/USER JOURNEY:* map out current versus expected user journey (see attached image). There are additional notes in the image file that highlight expected functionality.

![Image](https://user-images.githubusercontent.com/140492229/265929161-3edd6ecd-1b23-452d-b7d8-919d385941e0.jpg)

**Tasks**

- [ ] Review filter button and copy 
- [ ] Test quick filters functionality on mobile 
- [ ] UX and Design to improve map flow - loop in FED after this has been done 
- [ ] Investigate map results 
- [ ] Consider implications for city maps (there are slight differences in how the maps work and the buttons available)

**Comment by MichaelGrahamVS** [comment]
archiving this for now as it has been superseded by current Sprint work
