### ISSUE TITLE
(DESIGN/FED/UX) Create a sitewide sticky navigation

### ISSUE THREAD

**Issue by KirstyScott** [visitscotland/vs-component-library#65]
Implement a sitewide sticky navigation
**As** a user of visitscotland.com
**I want** a sticky navigation on the site
**So that** I don't need to scroll back to the top of the page to reach the navigation bar

**Acceptance Criteria**
When a user scrolls below the first window then the navigation bar remains at the top of screen.
Second ticket created for integration into component library (SE/FED task) 

**Tasks** 

- [x] Determine what functionality we want regarding maps 
- [x] UX to review wireframe and share findings with Sam for oversight 
- [ ] Ticket created for integration into the component library
- [ ] Main site nav bar to be sticky
- [ ] Global menu can scroll off screen and is not sticky

Original Jira ticket
https://jira.visitscotland.com/browse/VSD-397

Old wireframe: https://4ngt5o.axshare.com/#g=1&p=home 
Original UX & Design site requirements: https://4ngt5o.axshare.com/#g=1&p=header___mega_nav_details
