### ISSUE TITLE
(FED) Map Improvements - Zoom level

### ISSUE THREAD

**Issue by KirstyScott** [visitscotland/vs-component-library#92]
**Main Task** 
Change the zoom level of the main map of Scotland (https://www.visitscotland.com/places-to-go) so that all regions are displayed. 
For main, regional, and destination maps, determine: 
- how many levels of zoom are allowed for each map
- how will pins be displayed at each level

**Acceptance Criteria**
- The initial view should show as little of England and Ireland as possible and be large enough so that it is easy for users to engage with the map on mobile and desktop
- Shetland cannot be put in a box 
- The map functions as expected 

**Tasks**

- [x] Design to show how pins and clusters should look 
- [x] FED to explore if adjusting zoom is the only way 
- [ ] Design, FED and UX to look at aspect ratio and how the map sizes across different view ports 

**Useful Information** 
- For Main, the date comes from the CMS 
- Regional and city maps, the data comes from DMS (featured places comes from CMS)
