### ISSUE TITLE
(UX/Content) DMS: review category names on Destination Maps

### ISSUE THREAD

**Issue by KirstyScott** [visitscotland/vs-component-library#96]
While working on destination maps the  translations team reviewed the labels and categories used on the map.  They have some suggestions for changes. However, these are used in more places across the DMS than just maps. Need to review if changing these will have negative implications elsewhere on the site - conversation needs to happen with Karen Patton 

Additionally there is a request to change the name of the sub-category 'attractions' in category 'attractions'  as it appears like a mistake in the map. 

![Image](https://github.com/visitscotland/vs-component-library/assets/140492229/d12a00ee-51f2-4b1e-bda4-2edeb7a47493)

**Tasks**
First 
- [ ] Review if names could be changed - need to consult Karen Patton on this 
If names can be changed: 
- [ ] Ask Translation team for change suggestions 
- [ ] Determine how to make the name reflect that you need to book/have a ticket 
- [ ] UX and Content to work together find alternative to 'Attractions' filter 
- [ ] Understand how this work would be carried out by a Dev - would it change in multiple places?
